export const NOTIFY_SEND = 'notify/SEND';
export const NOTIFY_RECEIVE = 'notify/RECEIVE';

// UI
export const NOTIFICATION_OPEN = 'NOTIFICATION_OPEN';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const PIN_CHANGE = 'PIN_CHANGE';

/* Auth & Profile */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGOUT = 'LOGOUT';

export const RESETTING_REQUEST = 'RESETTING_REQUEST';
export const RESETTING_SUCCESS = 'RESETTING_REQUEST_SUCCESS';
export const RESETTING_FAIL = 'RESETTING_REQUEST_FAIL';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_REQUEST_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_REQUEST_FAIL';
export const PROFILE_SAVE_REQUEST = 'PROFILE_SAVE_REQUEST';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_REQUEST_SUCCESS';
export const PROFILE_SAVE_FAIL = 'PROFILE_SAVE_REQUEST_FAIL';

// Products
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_REQUEST_FAIL';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_REQUEST_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_REQUEST_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_REQUEST_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_REQUEST_FAIL';

export const PRODUCTS_FILTER_COLUMN = 'PRODUCTS_FILTER_COLUMN';

// Orders
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_REQUEST_SUCCESS';
export const ORDERS_FAIL = 'ORDERS_REQUEST_FAIL';

export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_REQUEST_SUCCESS';
export const ORDER_FAIL = 'ORDER_REQUEST_FAIL';

export const ORDERS_FILTER_COLUMN = 'ORDERS_FILTER_COLUMN';

// Users
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_REQUEST_SUCCESS';
export const USERS_FAIL = 'USERS_REQUEST_FAIL';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_FAIL = 'USER_REQUEST_FAIL';

export const USER_SAVE_REQUEST = 'USER_SAVE_REQUEST';
export const USER_SAVE_SUCCESS = 'USER_SAVE_REQUEST_SUCCESS';
export const USER_SAVE_FAIL = 'USER_SAVE_REQUEST_FAIL';
